Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,7 +15,7 @@ jobs:
 
     - name: Validate Stream Key
       run: |
-        if [ -z "${{ secrets.FB_STREAM_KEY }}" ]; then echo "Facebook Stream Key is missing!" && exit 1; fi
+        if [ -z "${FB_STREAM_KEY}" ]; then echo "Facebook Stream Key is missing!" && exit 1; fi
 
   stream:
     needs: validate
@@ -36,9 +36,9 @@ jobs:
 
         # Variables
         M3U8_URL="https://live4.beinconnect.us/YallaGoalApp/beINSports5.m3u8"
-        FB_STREAM_KEY="FB-122166135272260989-0-AbwTtkpEbN5l9t7h"  # Directly added the stream key
+        FB_STREAM_KEY="FB-122166135272260989-0-AbwTtkpEbN5l9t7h"  # Directly added the stream key here
         STREAM_URL="rtmps://live-api-s.facebook.com:443/rtmp/${FB_STREAM_KEY}"
-        
+
         # Retry logic (with 5 retries, 10 seconds apart)
         RETRY_COUNT=0
         MAX_RETRIES=5
